Repository cclib/cclib-data, pull requests merged in 2020-11, with the labels that each got.

#120 Added Turbomole example with raman.out
  .gitignore
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/GEO_OPT_CONVERGED
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/aoforce.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/auxbasis
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/basis
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/control
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/converged
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/coord
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/coord.xyz
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/coord0
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/define.input
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/define.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dftall.qsub
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dftall.qsub.o56815
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dipgrad
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dipl_a1
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dipl_b1
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dipl_b2
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dist.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/eig.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/eiger.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/energy
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/freeh.input
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/freeh.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/gradient
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/hessapprox
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/hessian
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/ir-spek.dat
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/job.last
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/job.start
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/mos
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/raman-spek.dat
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/raman.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/raman.qsub
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/ridft.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/rman_a1
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/rman_a2
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/rman_b1
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/rman_b2
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/spridft.qsub
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/statistics
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/vib.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/vib_normal_modes
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/vibspectrum
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/wherefrom
Labels: Turbomole, regression

#143 Revert " Added Turbomole example with raman.out"
  .gitignore
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/GEO_OPT_CONVERGED
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/aoforce.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/auxbasis
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/basis
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/control
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/converged
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/coord
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/coord.xyz
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/coord0
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/define.input
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/define.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dftall.qsub
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dftall.qsub.o56815
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dipgrad
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dipl_a1
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dipl_b1
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dipl_b2
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dist.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/eig.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/eiger.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/energy
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/freeh.input
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/freeh.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/gradient
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/hessapprox
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/hessian
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/ir-spek.dat
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/job.last
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/job.start
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/mos
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/raman-spek.dat
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/raman.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/raman.qsub
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/ridft.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/rman_a1
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/rman_a2
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/rman_b1
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/rman_b2
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/spridft.qsub
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/statistics
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/vib.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/vib_normal_modes
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/vibspectrum
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/wherefrom
Labels: maintenance

#144 Revert "Revert " Added Turbomole example with raman.out""
  .gitignore
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/GEO_OPT_CONVERGED
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/aoforce.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/auxbasis
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/basis
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/control
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/converged
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/coord
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/coord.xyz
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/coord0
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/define.input
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/define.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dftall.qsub
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dftall.qsub.o56815
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dipgrad
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dipl_a1
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dipl_b1
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dipl_b2
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/dist.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/eig.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/eiger.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/energy
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/freeh.input
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/freeh.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/gradient
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/hessapprox
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/hessian
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/ir-spek.dat
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/job.last
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/job.start
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/mos
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/raman-spek.dat
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/raman.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/raman.qsub
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/ridft.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/rman_a1
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/rman_a2
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/rman_b1
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/rman_b2
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/spridft.qsub
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/statistics
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/vib.out
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/vib_normal_modes
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/vibspectrum
  Turbomole/Turbomole7.2/au2_n22_cl_+_bp86-d3bj-deftzvp/wherefrom
Labels: maintenance

#142 Add one missing file to list and fix a typo
  regressionfiles.txt
Labels: maintenance

#141 test cases for issue #974
  QChem/QChem5.2/qchem_tddft_rpa.out
  QChem/QChem5.3/tddft.out
  regressionfiles.txt
Labels: QChem, regression
